
// setting 11 to input causes crashes

#define GARAGE_OPEN_SENSOR_PIN 10
#define GARAGE_CLOSED_SENSOR_PIN 9 /*9*/
#define GARAGE_OPEN_CONTROL_PIN 13
#define GARAGE_CLOSE_CONTROL_PIN 12
#define GARAGE_STATUS_LED_PIN 14

#define GARAGE_MAX_TRANSIT_SECONDS 30
#define GARAGE_SENSOR_POLL_MILLISECONDS 100
#define GARAGE_CONTROL_PULSE_MILLISECONDS 1000
